language: java
sudo: true
before_install:
  - chmod +x mvnw

addons:
  sonarcloud:
    organization: "esgi-4-al"

jobs:
  include:
    - stage: test
    name: "Test..."
    script:
      - ./mvnw clean test
      - stage: build
        name: "Build..."
        script:
          - ./mvnw clean package -DskipTests
      - stage: deploy
        name: "Deploy..."
