language: java
sudo: true
before_install:
  - chmod +x mvnw

jobs:
  include:
    - stage: test
      name: "Run tests..."
    - stage: build
      name: "Build..."
      script:
        - ./mvnw clean package -DskipTests
    - stage: deploy
      name: "Deploy..."
